<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Version>2.7.1</Version>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <AssemblyVersion>2.7.1</AssemblyVersion>
    <FileVersion>2.7.1</FileVersion>
    <PackageProjectUrl>https://github.com/httpjsonrpcnet/httpjsonrpcnet</PackageProjectUrl>
    <RepositoryUrl>https://github.com/httpjsonrpcnet/httpjsonrpcnet</RepositoryUrl>
    <PackageLicenseUrl></PackageLicenseUrl>
    <Description>JSON-RPC implementation over HTTP.</Description>
    <PackageTags>http json rpc json-rpc api</PackageTags>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackAsTool>False</PackAsTool>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommonServiceLocator" Version="2.0.7" />
    <PackageReference Include="Microsoft.Bcl.AsyncInterfaces" Version="9.0.7" />
    <PackageReference Include="System.ComponentModel.Annotations" Version="5.0.0" />
    <InternalsVisibleTo Include="HttpJsonRpc.Tests" />
    <PackageReference Include="Microsoft.AspNetCore.Cors" Version="2.3.0" />
    <PackageReference Include="Microsoft.AspNetCore.Server.Kestrel" Version="2.3.13" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.7" />
    <PackageReference Include="System.Text.Json" Version="9.0.7" />
    <None Include="..\..\README.md" Pack="true" PackagePath="\"/>
    <None Include="..\..\CHANGELOG.md" Pack="true" PackagePath="\"/>
  </ItemGroup>

</Project>
